//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers_dresses
    {
        public int id { get; set; }
        public long customer_id { get; set; }
        public int dress_id { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual dresses dresses { get; set; }
    }
}
