//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dresses()
        {
            this.customers_dresses = new HashSet<customers_dresses>();
        }
    
        public int id { get; set; }
        public int categoery_dress { get; set; }
        public byte[] color { get; set; }
        public int size { get; set; }
        public int price { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual colors colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customers_dresses> customers_dresses { get; set; }
        public virtual sizes sizes { get; set; }
    }
}
