//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class my_projectEntities : DbContext
    {
        public my_projectEntities()
            : base("name=my_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<colors> colors { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<customers_dresses> customers_dresses { get; set; }
        public virtual DbSet<dresses> dresses { get; set; }
        public virtual DbSet<sizes> sizes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<telephones> telephones { get; set; }
        public virtual DbSet<types> types { get; set; }
    }
}
